### ISSUE TITLE
Highlight color in URL bar obscures the text

### ISSUE THREAD

**Issue by tpoulos** [liri-project/liri-browser#118]
<img width="630" alt="screenshot 2015-10-07 21 12 03" src="https://cloud.githubusercontent.com/assets/2533239/10355284/1547fe0e-6d38-11e5-8c8f-5a52d51e93cd.png">

**Comment by VirusKA** [comment]
could this just be color choice? try yellow?

**Comment by Haroenv** [comment]
Yep, but the default colour is still wrong :)

**Comment by tim-sueberkrueb** [comment]
This was fixed long time ago with the new omnibox style ^^
