### ISSUE TITLE
Exit search shortcut mode 

### ISSUE THREAD

**Issue by tim-sueberkrueb** [liri-project/liri-browser#132]
After entering e.g. ytb there's no way to get back to normal url editing.
There could be the icon from the integrated mode as well as an binding to escape. 
(https://github.com/liri-browser/liri-browser/issues/104)

**Comment by danielfranca** [comment]
You can press backtab (shift + tab) to go back to normal url editing.

**Comment by tim-sueberkrueb** [comment]
@danielfranca yeah, I found that out recently as well :D. I think an exit button would be good to have though.

**Comment by danielfranca** [comment]
I think backtab is not very intuitive as well

**Comment by VirusKA** [comment]
backspace will most likely be the most intuitive.

**Comment by tim-sueberkrueb** [comment]
Fixed in  2985577, should we keep shift+tab though?

**Comment by pierremtb** [comment]
@tim-sueberkrueb Yeah let's keep it

**Comment by VirusKA** [comment]
i agree.

**Comment by tim-sueberkrueb** [comment]
ok :)
