### ISSUE TITLE
Webpage is down

### ISSUE THREAD

**Issue by ShalokShalom** [liri-project/liri-browser#135]
https://liri-browser.github.io/ leads me into a 404

**Comment by pierremtb** [comment]
We now have a domain : http://liriproject.me

**Comment by ShalokShalom** [comment]
Google and the  Github page here direct still to the old one.
The new page seems to be still in development, why drop the old one, beofre the new one is ready please ?

**Comment by tim-sueberkrueb** [comment]
@ShalokShalom We restructured our organization, sorry for that inconvenience. You're right, the action was probably a bit overhasty (which is my fault).

**Comment by tim-sueberkrueb** [comment]
You can access all browser infos [here](http://liriproject.me/browser/).
