### ISSUE TITLE
liri-browser.github.io returns 404

### ISSUE THREAD

**Issue by timwangdev** [liri-project/liri-browser#136]
http://liri-browser.github.io/

**Comment by tim-sueberkrueb** [comment]
@timwangdev Yes, we restructured our organization. Our new page is liriproject.me/. Don't worry about the empty homepage, it's pretty much WIP.

**Comment by tim-sueberkrueb** [comment]
http://liriproject.me/browser/index.html#discover

**Comment by timwangdev** [comment]
You'd better update the link in the description, from http://liri-browser.github.io/ to http://liriproject.me/browser/ or http://liri-project.github.io/

**Comment by tim-sueberkrueb** [comment]
@timwangdev oh, right, thanks :)
