### ISSUE TITLE
Google shows the old webpage

### ISSUE THREAD

**Issue by ShalokShalom** [liri-project/liri-browser#138]
https://www.google.at/search?q=liri%20browser&rct=j

**Comment by tim-sueberkrueb** [comment]
@ShalokShalom I requested Google to remove the obsolete URL. The old url shouldn't appear anymore soon.

**Comment by danielhickman** [comment]
I thought part of what decides which version you go to is your user agent. May that need to be spooffed?

**Comment by tim-sueberkrueb** [comment]
The is now removed from Googles index.
