### ISSUE TITLE
Liri Browser's "contribute" page takes you to the wrong Github project

### ISSUE THREAD

**Issue by Dyras** [liri-project/liri-browser#139]
Hi. I've had a really bad day today so I'm going to keep this short. If you go on http://liriproject.me/browser/index.html#code and click "GITHUB" you get taken to https://github.com/liri-browser which is completely empty.

Looks like a really clean and modern browser by the way, I just wish you didn't use Google as the standard start page/search engine. They already know waaaaaaaaaay too much about me already.

**Comment by pierremtb** [comment]
@Dyras Thank you for pointing this out. Regarding the default search engine, Google is the most used, so, for a lot of people, it's more convenient to have it by default. However you can change it in settings.

**Comment by pierremtb** [comment]
Done

**Comment by Dyras** [comment]
@pierremtb I was thinking about Disconnect or something similar that uses Google without all the tracking.

**Comment by tim-sueberkrueb** [comment]
@Dyras just for the future: please report website related issues [here](https://github.com/liri-project/liri-project.github.io). Thank you!
