### ISSUE TITLE
Bug( Probably)

### ISSUE THREAD

**Issue by NajeraP95** [liri-project/liri-browser#140]
When I close all the tabs. I can't open a new tab. I try unninstall the browser and install again but this bug still after the install (My english don't is so good)

**Comment by tim-sueberkrueb** [comment]
How did you install the browser? Which version are you running?
Most probably this problem does no longer exist in the code's current development state.

**Comment by NajeraP95** [comment]
I'm running the v0.3. When I close all the tabs, the adressbar and the tabsbar disappear and  It's necessary press Ctrl+T for Open a new tab

**Comment by tim-sueberkrueb** [comment]
@NajeraP95 yeah, that's fixed now. Thanks for reporting.
