### ISSUE TITLE
Add a PDF viewer

### ISSUE THREAD

**Issue by pierremtb** [liri-project/liri-browser#145]
Could be simple using Mozilla's PDF.js

**Comment by VirusKA** [comment]
me gusta

**Comment by pierremtb** [comment]
I can move this issue to 0.4 with a small workaround for now : 
we can access to a full-featured pdf viewer by going to https://docs.google.com/viewer?url=[pdfUrlHere]

For example : 
https://docs.google.com/viewer?url=http://www.indire.it/wp-content/uploads/2015/08/pdf-sample.pdf

**Comment by pierremtb** [comment]
Implemented the previous workaround : 
![capture d ecran de 2016-01-01 19-25-56](https://cloud.githubusercontent.com/assets/10795683/12071633/963c47d4-b0b5-11e5-8156-e62e455251ba.png)
![capture d ecran de 2016-01-01 19-26-02](https://cloud.githubusercontent.com/assets/10795683/12071634/9b7da8aa-b0b5-11e5-9e26-5468d56e2449.png)

I close the issue for now, since there are other things to do ATM which are more important.
