### ISSUE TITLE
Omniplets : components which handle suggestions in Omnibox

### ISSUE THREAD

**Issue by pierremtb** [liri-project/liri-browser#146]
TODO: 
- [x] Backend
- [x] Display on typing in Omnibox
- [x] Display with Integrated mode
- [x] Display correctly in Mobile mode
- [x] Navigate with keys
- [x] Add Bookmarks Omniplet
- [x] Add History Omniplet
- [x] Add Calculator Omniplet
- [x] Add Weather Omniplet
- [x] Add a Omniplets settings section
- [x] Refactor Omniplets into a plugins-like system (not in a sandbox though)
- [ ] Improve the display with Integrated mode
- [ ] Fix some align problems

**Comment by tim-sueberkrueb** [comment]
\0/ awesome!
We should combine this with #56.
BTW this is a duplicate of #7 :)

**Comment by pierremtb** [comment]
Done :)
![capture d ecran de 2015-10-27 14-28-36](https://cloud.githubusercontent.com/assets/10795683/10759327/0bfd405a-7cb7-11e5-80a3-efd0ddc996af.png)

**Comment by danielfranca** [comment]
Looks awesome, congrats :)

**Comment by lawrencenull** [comment]
Fantastic!

**Comment by VirusKA** [comment]
oh my gawd amazing

**Comment by danielfranca** [comment]
Should we combine the duckduck go suggestions with history?

**Comment by tim-sueberkrueb** [comment]
@danielfranca yes, that would be nice to have.

**Comment by pierremtb** [comment]
Added history and bookmark related suggestions
![capture d ecran de 2015-11-09 23-30-47](https://cloud.githubusercontent.com/assets/10795683/11048773/1b5fcb0c-873a-11e5-98cd-ad5df9c57461.png)

**Comment by tim-sueberkrueb** [comment]
\0/ great :)

**Comment by danielfranca** [comment]
Loved the idea to have it component based :) Nice job!

**Comment by VirusKA** [comment]
Genius!

**Comment by pierremtb** [comment]
![capture d ecran de 2015-11-12 09-41-16](https://cloud.githubusercontent.com/assets/10795683/11114013/8fd1e202-8921-11e5-918f-f3d3506a9434.png)

**Comment by VirusKA** [comment]
nice!

**Comment by pierremtb** [comment]
So this will be now splitted into two different issues : 
- #164, which deals with the OmniboxSuggestions view
- #162, which deals with plugins (Omniplets included)
