### ISSUE TITLE
Find a way to display the source locally

### ISSUE THREAD

**Issue by pierremtb** [liri-project/liri-browser#147]

**Comment by VirusKA** [comment]
I feel this should be set back to 1.0 production time. Building features and squashing bugs is more important IMO

**Comment by VirusKA** [comment]
Any ideas on how to do this?

**Comment by tim-sueberkrueb** [comment]
@VirusKA a simple solution would be to just open the source code viewer html and js code and load it into a webview.

**Comment by VirusKA** [comment]
@tim-sueberkrueb that's pretty smart. Hopefully, you guys can implement it.

**Comment by pierremtb** [comment]
Yeah I only need to figure out how to handle it with qrc. Sadly I don't
have time to work on Liri atm.

**Comment by pierremtb** [comment]
The source code viewer will be included inside Chromium Dev Tools, so there's no need for this anymore.
