### ISSUE TITLE
Open new tab is empty

### ISSUE THREAD

**Issue by elav** [liri-project/liri-browser#161]
Hello. I installed Liri Browser from AUR and the latest git, to open a link in a new tab, open the empty tab. I use Manjaro 64bits.

**Comment by VirusKA** [comment]
Screenshot?

**Comment by elav** [comment]
A screenshot of a tab in white? ¬_¬

**Comment by tim-sueberkrueb** [comment]
@elav thanks for reporting. This is a bug.

**Comment by tim-sueberkrueb** [comment]
(only affects middle button action)

**Comment by elav** [comment]
Your welcome! ;) I have many expectations about Liri Browser
