### ISSUE TITLE
Page head is above page content

### ISSUE THREAD

**Issue by tim-sueberkrueb** [liri-project/liri-browser#168]
Affects any sub page (settings, custom searches ...)
![bildschirmfoto vom 2015-11-16 15-42-07](https://cloud.githubusercontent.com/assets/11774614/11184546/9f307f74-8c78-11e5-95d7-3ab1d029a225.png)
@pierremtb any idea why this happens?

**Comment by pierremtb** [comment]
Fixed
![capture d ecran de 2016-01-01 19-39-40](https://cloud.githubusercontent.com/assets/10795683/12071660/240cc63c-b0b7-11e5-8703-f24edaad10a5.png)
