### ISSUE TITLE
Add common keyboard shortcuts

### ISSUE THREAD

**Issue by Arial7** [liri-project/liri-browser#171]
Hey guys, it would be nice if you would add some common browser keyboard shortcuts.

Some examples:

`ctrl+tab` cycle tabs forward
`ctrl+shift+tab` cycle tabs backwards
`ctrl+l` focus unibar
`backspace` change to last page in history
`shift+backspace` change to next page in history

**Comment by tim-sueberkrueb** [comment]
@Arial7 thx for reporting :) Didn't even know about that Backspace Shortcut ^^

**Comment by Arial7** [comment]
Really? :D
The most important for me though is `ctrl+l`

**Comment by tim-sueberkrueb** [comment]
@Arial7 :)
