### ISSUE TITLE
problem with google+

### ISSUE THREAD

**Issue by aggalex** [liri-project/liri-browser#190]
I opened google+. I have the new UI of Google+. But google plus is keeping loading again and again. All the time, while only the background color is shown. This problem is reproducable every time I open Google+.

**Comment by pierremtb** [comment]
Which version are you using?

**Comment by aggalex** [comment]
The latest, downloaded from github 2 days ago.

**Comment by pierremtb** [comment]
Ok. It's probably caused by the old Chromium version shipped with Qt5.5.
Our next release, v0.4, will be compiled with Qt5.6, which brings a new
version of Chromium.

**Comment by aggalex** [comment]
That's great! Thanks!

**Comment by pierremtb** [comment]
Just compiled with Qt5.6, and it seems fixed : 
![capture d ecran de 2015-12-30 14-38-26](https://cloud.githubusercontent.com/assets/10795683/12051378/2cc0a132-af03-11e5-8289-736a4e4549e2.png)

**Comment by aggalex** [comment]
Great!!!! Thank you all! Cheers! Have a nice new year!
