### ISSUE TITLE
New Tab on Launch

### ISSUE THREAD

**Issue by Crocodile73** [liri-project/liri-browser#191]
Using Windows 10 and version 0.3, everytime i try to run the browser, all i get is a new tab, and there is nothing here yet. There is no toolbar or address bar, nothing works, any ideas. This browser looks great, and would like to use it.

**Comment by tim-sueberkrueb** [comment]
@Crocodile73 Sorry for this inconvenience, this bug was already fixed in the code. You can resolve this for now by pressing Ctrl+T to add a new tab. Hope you enjoy Liri besides from that :)
