### ISSUE TITLE
Where is the viewer?

### ISSUE THREAD

**Issue by Mrnumbers9** [liri-project/liri-browser#192]
Is it just my build, or does the source code viwer lead to a GH 404 page...

**Comment by Mrnumbers9** [comment]
![omg6](https://cloud.githubusercontent.com/assets/12434477/12080370/603e9744-b250-11e5-816f-cd3b039b16b6.png)

**Comment by tim-sueberkrueb** [comment]
@Mrnumbers9 yeah, sorry for this inconvenience. This bug is already fixed in the source. Liri v0.4 will include this fix.
