### ISSUE TITLE
Update qml-material

### ISSUE THREAD

**Issue by SolarAquarion** [liri-project/liri-browser#194]
Gtk-Message: Failed to load module "pantheon-filechooser-module"
/home/solaraquarion/.gtkrc-2.0:19: Unable to find include file: "~/.gtkrc-2.0.mine"
Couldn't open config file.
QQmlApplicationEngine failed to load component
qrc:/qml/DesktopApplication.qml:25 Type BrowserWindow unavailable
qrc:/qml/BrowserWindow.qml:517 Type BrowserPage unavailable
qrc:/qml/BrowserPage.qml:160 Type BookmarksBar unavailable
qrc:/qml/BookmarksBar.qml:26 Type BookmarkItem unavailable
qrc:/qml/BookmarkItem.qml:120 Popover is not a type

**Comment by iBeliever** [comment]
I just released a new version of the Material framework this uses, and as part of that, updated the versions of several components that were added in v0.2. So basically, all the `Material 0.1` imports need to be updated to `Material 0.2`. There's a handy `normalize_imports.sh` script in qml-material that can help with this.

**Comment by tim-sueberkrueb** [comment]
@iBeliever As far as I understand, the whole point about QML imports with version numbers is to keep the library up-/downwards compatible, right? I'd suggest to handle breaking changes by using separate files (see how the `ubuntu-ui-tolkit` does that). E.g. you could have
* modules/Material
  * 0.1
    * Component.qml ...
  * 0.2
    * Component.qml ...

And add the relevant data in `qmldir`. The way it is now every project breaks on every update which I think is bad developer experience. That's just my opinion, of course.

**Comment by iBeliever** [comment]
@tim-sueberkrueb Right... the problem was that I added new components (in this case, the Popover) after v0.1, so the import should have been 0.2 (so you have to import 0.2 to access new features in Material 0.2). However, I added them with an import of 0.1, so I had to fix that when I did the release. Normally this won't happen. For example, any components added now will have an import of 0.3, so you'd have to do `import Material 0.3`.

**Comment by tim-sueberkrueb** [comment]
@iBeliever all right.

**Comment by iBeliever** [comment]
Just fixed the imports. Sorry again guys for the mess up. I'm make sure future additions to qml-material are added with the right version instead of updating them right before release.

**Comment by tim-sueberkrueb** [comment]
@iBeliever cool, thank you :)
