### ISSUE TITLE
Can't start on Antergos

### ISSUE THREAD

**Issue by Collinthegeek** [liri-project/liri-browser#199]
Repository version (liri-browser-git-0.3.r239.gf11a68d-1):
$ liri-browser
Couldn't open config file.
QQmlApplicationEngine failed to load component
qrc:/qml/DesktopApplication.qml:25 Type BrowserWindow unavailable
qrc:/qml/BrowserWindow.qml:517 Type BrowserPage unavailable
qrc:/qml/BrowserPage.qml:160 Type BookmarksBar unavailable
qrc:/qml/BookmarksBar.qml:26 Type BookmarkItem unavailable
qrc:/qml/BookmarkItem.qml:120 Popover is not a type

Segmentation fault (core dumped)

Github version (160e00a9b3de74a229321a3eed2c0ee1dd455ca0):
$ liri-browser
Couldn't open config file.
qml: Locale name: C
qrc:/qml/BaseApplication.qml:250: TypeError: Cannot read property 'length' of undefined
qrc:/qml/BrowserTabBar.qml:21:5: QML ListView: Binding loop detected for property "width"
<Unknown File>: QML QQuickLayoutAttached: Binding loop detected for property "minimumWidth"
qrc:/qml/BrowserWebView.qml:6:1: module "QtWebEngine" version 1.2 is not installed
qml: Error
qml: Warning, loader is not ready!
file:///usr/lib/qt/qml/QtQuick/Controls/Styles/Material/TextFieldStyle.qml:35: ReferenceError: echoMode is not defined
qrc:/qml/TabBarItemDelegate.qml:104:33: Unable to assign null to QUrl
qrc:/qml/TabBarItemDelegate.qml:127:31: Unable to assign null to QString
qrc:/qml/TabBarItemDelegate.qml:320:27: Unable to assign null to QString
qrc:/qml/RightDrawer.qml:30:15: Unable to assign [undefined] to QQmlListProperty<QQuickItem>
qrc:/qml/ColorChooser.qml:48:24: Unable to assign [undefined] to QColor
qrc:/qml/ColorChooser.qml:48:24: Unable to assign [undefined] to QColor
qrc:/qml/ColorChooser.qml:48:24: Unable to assign [undefined] to QColor
qrc:/qml/ColorChooser.qml:48:24: Unable to assign [undefined] to QColor
qrc:/qml/ColorChooser.qml:48:24: Unable to assign [undefined] to QColor
qrc:/qml/ColorChooser.qml:48:24: Unable to assign [undefined] to QColor
qrc:/qml/Omnibox.qml:130:20: Unable to assign [undefined] to QColor
qrc:/qml/Omnibox.qml:125:15: Unable to assign null to QString
qrc:/qml/Omnibox.qml:214:20: Unable to assign [undefined] to QColor
qrc:/qml/FullscreenBar.qml:31:21: Unable to assign null to QUrl
qrc:/qml/BrowserPage.qml:247:20: Unable to assign [undefined] to QColor
qrc:/qml/RightDrawer.qml:30:15: Unable to assign [undefined] to QQmlListProperty<QQuickItem>
qrc:/qml/RightDrawer.qml:30:15: Unable to assign [undefined] to QQmlListProperty<QQuickItem>
qrc:/qml/BrowserPage.qml:346:16: Unable to assign bool to QColor
qrc:/qml/Settings.qml:477:35: Unable to assign double to QQuickAnchorLine
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
file:///usr/lib/qt/qml/QtQuick/Controls/Styles/Material/TextFieldStyle.qml:35: ReferenceError: echoMode is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
qrc:/qml/ColorPicker.qml:41: ReferenceError: chbCustomColor is not defined
file:///usr/lib/qt/qml/QtQuick/Controls/Styles/Material/TextFieldStyle.qml:35: ReferenceError: echoMode is not defined
Loading plugins
Loading plugin "Desktop" "/home/collin/Desktop"
Couldn't open manifest file.
Plugin API version: ""
Plugin uses unknown API version. Cancel loading.
Loading plugin "Downloads" "/home/collin/Downloads"
Couldn't open manifest file.
Plugin API version: ""
Plugin uses unknown API version. Cancel loading.
Loading plugin "Papyros" "/home/collin/Papyros"
Couldn't open manifest file.
Plugin API version: ""
Plugin uses unknown API version. Cancel loading.
Triggered event "load"
Segmentation fault (core dumped)

**Comment by tim-sueberkrueb** [comment]
Sorry for this, see #170.
