### ISSUE TITLE
Failure to save settings

### ISSUE THREAD

**Issue by wayneoutthere** [liri-project/liri-browser#201]
When I save my settings on my Liri browser running on Ubuntu mobile, the settings don't save.  For example, I change the startup page to duckduckgo instead of default, click 'save' and then it doesn't actually save.  Hope this helps and have a nice day.  Love the bones of this browser!

**Comment by tim-sueberkrueb** [comment]
Hey @wayneoutthere, sorry for the inconvenience, we're aware of that. See #57 and #169.
