### ISSUE TITLE
Zooming does not work on Windows 10

### ISSUE THREAD

**Issue by D1G1TE** [liri-project/liri-browser#226]
Both Portable and Install version are behaving same. When I press "CTRL + plus" or "CTRL + minus" or use CTRL + mouse wheel. Nothing happens, nothings zoomed.

**Comment by tim-sueberkrueb** [comment]
This feature was implemented for v0.4, see https://github.com/liri-project/liri-browser/issues/150.

**Comment by D1G1TE** [comment]
Great! :)
