### ISSUE TITLE
How can I get out of this screen?

### ISSUE THREAD

**Issue by Suburbanno** [liri-project/liri-browser#233]
![screenshot_5](https://cloud.githubusercontent.com/assets/13632826/18005252/49b157d6-6b6f-11e6-92ed-1050a8a497b0.png)

**Comment by pierremtb** [comment]
Try CTRL+T

Le ven. 26 août 2016 14:29, Vinicius Ferreira <notifications@github.com> a
écrit :

**Comment by danielhickman** [comment]
That doesn't work at least for me on Windows 10. I guess integrated toolbars are for Linux?

**Comment by timsueberkrueb** [comment]
@Suburbanno Please note that the development has moved to [lirios/browser](https://github.com/lirios/browser).
