### ISSUE TITLE
Search predictions in address bar

### ISSUE THREAD

**Issue by tim-sueberkrueb** [liri-project/liri-browser#7]
depends on #2

**Comment by tim-sueberkrueb** [comment]
This has to wait until #14 is finished.

**Comment by VirusKA** [comment]
Is this another upstream thing?

**Comment by iBeliever** [comment]
@VirusKA No. Search suggestions or history recommendations are specific to Liri browser. It's not a general toolkit thing.

**Comment by VirusKA** [comment]
oh ok. sounds good.

**Comment by jmc-figueira** [comment]
Working on it, hopefully will be done by tomorrow. Sorry for taking some time with it, but college has been taking a chunk of my time.

**Comment by tim-sueberkrueb** [comment]
@jmc-figueira cool, good luck with it! (Also you don't have to be sorry because of the time).

**Comment by VirusKA** [comment]
yeah take your time jmc

**Comment by VirusKA** [comment]
should this be closed in favor of #146?

**Comment by tim-sueberkrueb** [comment]
@VirusKA yes, thanks :)
