### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by revanthpobala** [liri-project/liri-browser#80]
Well!. I have installed the browser on Windows 10. When I open the browser it is crashing. After a few minutes it became normal and it crashed again. The source code viewer is very slow. I hope that in next iterations of the browser it will become stable. 

Cheers Guys!. Very good material design

**Comment by Polyg0n** [comment]
What were you doing when the crash occurred, and what are you system specs? 
That way I can better bug test this.

**Comment by revanthpobala** [comment]
My system specs are i5 intel processor, 8GB RAM, Lenovo Flexpad.Memory used by Liri is 165 MB. I opened a new tab. That's it

**Comment by Polyg0n** [comment]
Hmm. I will do some digging to see if I can solve this. 

Thanks for the bug report!

**Comment by revanthpobala** [comment]
Sure PolygOn.

**Comment by tdtmusic** [comment]
Same thing. Just installed on Windows 7 x64 and it crashes on start.

**Comment by Polyg0n** [comment]
You're welcome @revanthpobala 
And thanks for the log @tdtmusic! That will help with the debugging process!

**Comment by I-am-Groot** [comment]
I just downloaded this browser and installed it on my Dell Latitude e6420 (Core i5 4Gb ram) running Ubuntu *(32bit)* and after the installation, it wont startup. I tried starting it up from the terminal with **"liri-browser"** which didnt work.
I then navigated to **"/opt/liri/ "** and entered **"sudo bash run-liri.sh"** but i got this
**"run-liri.sh: line 17: /opt/liri-browser/liri-browser: cannot execute binary file: Exec format error"**

**Comment by tim-sueberkrueb** [comment]
@I-am-Groot As mentioned [here](https://github.com/liri-browser/liri-browser#ubuntu--debian-64-bit-only) and [here](https://github.com/liri-browser/liri-browser#any-linux-64-bit-only), our binary packages for Linux are 64bit only (yet). You'd have to [build it yourself](https://github.com/liri-browser/liri-browser#build-on-linux).

**Comment by I-am-Groot** [comment]
I followed your links and tried to build it using the automated build script but it looks like it would just build me a 64bit version. 
So, how exactly do i build a 32bit version? I am a little new to building stuff on linux and git

**Comment by tim-sueberkrueb** [comment]
@I-am-Groot oh, I see. You need to download the "qt-unified-linux-x86-online.run" from [here](http://download.qt.io/official_releases/online_installers/). Execute the file using ```sh qt-unified-linux-x86-online.run``` and follow the installation instruction in order to install Qt 5.5. Then you can follow the [instructions](https://github.com/liri-browser/liri-browser#instructions) to setup QML-Material and to download and build Liri. When using qmake, just use the absolute path e.g ```home/you/Qt/5.5/gcc_x<your_arch>/bin/qmake```.

**Comment by th3an7** [comment]
Hi guys
The same problem as OP. Installed v0.3 with .exe (I've also tried .zip but the same problem). On my side it crashes immediately after start. Can't do anything. Tried running in admin mode and with compatibility settings but it did nothing...

SOLUTION:
I looked at log in event viewer (I am on Win10 Insider Preview 10565) and it showed me the same problem as @tdtmusic. I went to windows\system32 and looked for ig4icd32.dll file but there was no such a file. I downloaded that .dll and copied to Liri Brower catalogue and BAM - it starts. Now I am testing if it crashes but for now it works just fine.

**Comment by subirats345** [comment]
The same problem. Crash on Windows 10 (Build 10576).

**Comment by th3an7** [comment]
@subirats345 Check your event viewer logs. If it has the same error than mine - search for dll file and paste it in Brower catalogue. It should start without crashing.

**Comment by subirats345** [comment]
Yes. With the dll works perfectly. Thanks. For when a new version? The browser is awesome!

**Comment by timsueberkrueb** [comment]
If you're still interested, have a look at the [new repository](https://github.com/lirios/browser/).
