### ISSUE TITLE
Translations not working on Ubuntu Touch

### ISSUE THREAD

**Issue by jmc-figueira** [liri-project/liri-browser#89]
Maybe it's supposed to be like it is for now, but after building liri from git to test the translation I recently provided, I noticed it wasn't working. The app is still in english. I checked if perhaps Qt wasn't detecting my locale correctly, but sure enough, it was.

**Comment by tim-sueberkrueb** [comment]
@jmc-figueira yeah, it's currently disabled.

**Comment by tim-sueberkrueb** [comment]
Okay, it works now for the desktop thanks to @Ilya87.
There are still something to do to make it work on Ubuntu Touch.

**Comment by tim-sueberkrueb** [comment]
Fixed.
